### PR TITLE
fix: add mutex to SSEServer to avoid data race between Start and Shutdown; fix test error on Windows (#166 #172)

### LINKED ISSUE #166: Data race between Start and Shutdown in SSEServer struct
There is data race between 

[func (s *SSEServer) Start(addr string) error](https://github.com/mark3labs/mcp-go/blob/37ac814a6010484d409bef15f6f4b015f486bdaa/server/sse.go#L192C2-L192C10)

and 

[func (s *SSEServer) Shutdown(ctx context.Context) error](https://github.com/mark3labs/mcp-go/blob/37ac814a6010484d409bef15f6f4b015f486bdaa/server/sse.go#L203C2-L203C4)

### LINKED ISSUE #172: There are some errors when I run tests on Windows
When I run the command "go test -v './...'", there is the error
```
--- FAIL: TestStdioMCPClient (0.68s)
    stdio_test.go:42: Failed to create client: failed to start stdio transport: failed to start command: exec: "C:\\Users\\86175\\AppData\\Local\\Temp\\mockstdio_server": executable file not found in %PATH%
FAIL
FAIL    github.com/mark3labs/mcp-go/client      0.737s
```

So we should make it runnable on Windows

### PR DESCRIPTION
**Pull request by Wood-Q**
## What this PR does

1. This PR fixes a data race issue between `SSEServer.Start` and `SSEServer.Shutdown` by adding a `sync.RWMutex` to the `SSEServer` struct. 
2. Fix test error on Windows

- `Start` uses `mu.Lock` when setting `s.srv`
- `Shutdown` uses `mu.RLock` when accessing `s.srv`
- Add `'.exe'` to `mockServerPath`

## Related Issue

Closes #166
Closes #172

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved server shutdown reliability by ensuring all active sessions are properly closed.
  - Enhanced thread safety to prevent potential issues during server start and shutdown.
  - Fixed test compatibility for Windows by correctly handling mock server executable filenames.

### CODE REVIEW

File: server/sse.go [hunk 1]
```diff
@@ -189,18 +191,25 @@ func NewTestServer(server *MCPServer, opts ...SSEOption) *httptest.Server {
...
 // Shutdown gracefully stops the SSE server, closing all active sessions
 // and shutting down the HTTP server.
 func (s *SSEServer) Shutdown(ctx context.Context) error {
-	if s.srv != nil {
+	s.mu.RLock()
+	srv := s.srv
+	s.mu.RUnlock()
+
+	if srv != nil {
+		// 关闭所有会话
```
Comment (ezynda3) [inline server/sse.go:212]: Could you translate to English please :)

Comment (ezynda3) [inline server/sse.go:212]: Translate to English please :)

**Review by ezynda3 — CHANGES_REQUESTED** [review]

File: server/sse.go (hunk 1 above)
Comment (Wood-Q) [reply server/sse.go]: sorry, I have deleted the annotation :)
