### PR TITLE
fix: resolve stdio transport race condition for concurrent tool calls

### LINKED ISSUE #528: bug: bufio.Reader is not thread-safe
# Problem Description

When using the `github.com/mark3labs/mcp-go` library for stdio-based MCP servers, a race condition occurs after exactly 2-4 concurrent tool calls, causing:

- `Error reading input: read /dev/stdin: bad file descriptor`
- `write |1: broken pipe` errors
- Complete server failure requiring restart
- 0% success rate for subsequent tool calls

# Root Cause Analysis

The MCP-Go library has a **hardcoded race condition** in `/server/stdio.go`:

```go
// Problematic code in MCP-Go library
if baseMessage.Method == "tools/call" {
    go func() {  // ❌ RACE CONDITION: Multiple goroutines compete for same stdin
        response := s.server.HandleMessage(ctx, rawMessage)
        if response != nil {
            s.writeResponse(response, stdout)
        }
    }()
}
```

**The Issue:**

- Multiple goroutines created for concurrent tool calls
- All goroutines access the same `bufio.Reader` on stdin
- `bufio.Reader` is **NOT thread-safe**
- Concurrent access corrupts the file descriptor
- Results in permanent stdin corruption

# After trying many workarounds for hours, Claude said:

The only reliable fix is to **completely replace** the MCP-Go stdio server with a custom synchronous implementation that eliminates all goroutines.

# The fix worked but I would like to use the mcp-go stdio

### PR DESCRIPTION
**Pull request by ezynda3**
## Description
This PR fixes a critical race condition in the stdio transport that occurs when multiple concurrent tool calls are made. The issue causes "bad file descriptor" errors and permanent stdin corruption after 2-4 concurrent calls.

Fixes #528

## Type of Change
- [x] Bug fix (non-breaking change that fixes an issue)
- [x] Tests only (no functional changes)

## Checklist
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the documentation accordingly

### Root Cause
The stdio transport was spawning a new goroutine for each `tools/call` request to avoid blocking on sampling requests. However, multiple goroutines were accessing the same `bufio.Reader` on stdin, which is not thread-safe. This led to corrupted reads and permanent stdin failure.

### Solution
Replaced the goroutine-per-request pattern with a worker pool architecture:
- Fixed pool of worker goroutines (default: 5, configurable)
- Buffered queue for tool calls (default: 100 capacity, configurable)
- Mutex protection for concurrent writes
- Graceful shutdown with proper cleanup

### Testing
- Added comprehensive test for concurrent tool calls
- All existing tests pass
- Race detector confirms no race conditions
- Maintains full backward compatibility

🤖 Generated with [opencode](https://opencode.ai)

## Summary by CodeRabbit

* **New Features**
  * Improved concurrent processing of "tools/call" requests with a configurable worker pool and queue limits.
  * Added options to customize worker thread count and queue size for tool call handling.

* **Bug Fixes**
  * Enhanced output handling to prevent issues from simultaneous writes during concurrent processing.

* **Tests**
  * Added tests verifying concurrent tool call handling, response correctness, and configuration option boundaries.

### CODE REVIEW

File: server/stdio.go [hunk 1]
```diff
@@ -50,6 +64,28 @@ func WithStdioContextFunc(fn StdioContextFunc) StdioOption {
...
 }
 
+// WithWorkerPoolSize sets the number of workers for processing tool calls
+func WithWorkerPoolSize(size int) StdioOption {
+	return func(s *StdioServer) {
+		if size > 0 && size <= 100 {
+			s.workerPoolSize = size
+		} else if size > 100 {
+			s.errLogger.Printf("Worker pool size %d exceeds maximum (100), using default: %d", size, s.workerPoolSize)
+		}
```
Comment (dugenkui03) [inline server/stdio.go:76]: When the size exceeds the maximum limit, falling back to the default value (100) is not appropriate, as the user clearly expects a larger queue size. maximum seems to be a better choice.

File: server/stdio.go [hunk 2]
```diff
@@ -50,6 +64,28 @@ func WithStdioContextFunc(fn StdioContextFunc) StdioOption {
...
+}
+
+// WithQueueSize sets the size of the tool call queue
+func WithQueueSize(size int) StdioOption {
+	return func(s *StdioServer) {
+		if size > 0 && size <= 10000 {
+			s.queueSize = size
+		} else if size > 10000 {
+			s.errLogger.Printf("Queue size %d exceeds maximum (10000), using default: %d", size, s.queueSize)
+		}
```
Comment (dugenkui03) [inline server/stdio.go:89]: Using maximum value would be better (instead of default value)

**Review by ezynda3 — COMMENTED** [review]
Fixed: 0ee38c43

File: server/stdio.go (hunk 1 above)
Comment (ezynda3) [reply server/stdio.go:76]: Fixed: 0ee38c43

File: server/stdio.go (hunk 2 above)
Comment (ezynda3) [reply server/stdio.go:89]: Fixed: 0ee38c43

**Review by dugenkui03 — APPROVED** [review]
