### PR TITLE
fix: add ErrUnauthorized sentinel for static token 401 responses

### LINKED ISSUE #511: bug: `401 Unauthorized` is handled improperly in streamable HTTP impl
## Description

When using a static token (in my case I'm using a GitHub PAT to access the GitHub MCP server), a `401 Unauthorized` response is not handled correctly when calling `client.Initialize`.

## Code Sample

https://github.com/mark3labs/mcp-go/blob/ef2e795/client/transport/streamable_http.go#L267-L272

## Logs or Error Messages

An error is returned: `"request failed with status 401: unauthorized: unauthorized: AuthenticateToken authentication failed\n"`, but a sentinel error should be returned in this case.

## Possible Solution

Handle the `c.oauthHandler == nil` specifically.
I'm not sure if this current design is intentional or not; I'm happy to contribute a fix.

### PR DESCRIPTION
**Pull request by ezynda3**
## Description

Adds a new `ErrUnauthorized` sentinel error that allows users to programmatically detect 401 Unauthorized responses when using static token authentication (e.g., GitHub PATs via `WithHTTPHeaders` or `WithHTTPHeaderFunc`).

Previously, static token users received generic error messages making it impossible to distinguish authentication failures from other HTTP errors. This change introduces a sentinel error that can be checked with `errors.Is()`.

Fixes #511

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] MCP spec compatibility implementation
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Code refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Tests only (no functional changes)
- [ ] Other (please describe):

## Checklist

- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the documentation accordingly

### New Sentinel Error
- Added `ErrUnauthorized = fmt.Errorf("unauthorized (401)")` to transport package
- Follows existing pattern used by `ErrSessionTerminated`

### Updated Error Handling (5 locations)
**StreamableHTTP:**
- `SendRequest`: Returns `ErrUnauthorized` for 401s when OAuth not configured
- `SendNotification`: Same logic

**SSE:**
- `Start`: Returns `ErrUnauthorized` for 401s when OAuth not configured  
- `SendRequest`: Same logic
- `SendNotification`: Same logic

### Test Coverage
- Added 2 tests for StreamableHTTP (SendRequest and SendNotification)
- Added 3 tests for SSE (Start, SendRequest, SendNotification)
- All tests verify `errors.Is(err, transport.ErrUnauthorized)` works correctly

### Before
```go
transport, _ := transport.NewStreamableHTTP(
    "https://api.github.com/mcp", 
    transport.WithHTTPHeaders(map[string]string{
        "Authorization": "Bearer invalid-token",
    }),
)

_, err := transport.SendRequest(ctx, request)
// err: generic error message with status 401
// Cannot programmatically detect authentication failure
```

### After
```go
transport, _ := transport.NewStreamableHTTP(
    "https://api.github.com/mcp", 
    transport.WithHTTPHeaders(map[string]string{
        "Authorization": "Bearer invalid-token",
    }),
)

_, err := transport.SendRequest(ctx, request)
if errors.Is(err, transport.ErrUnauthorized) {
    // Can now detect and handle authentication failures
    log.Println("Authentication failed - check your token")
}
```

## Backward Compatibility

✅ **Fully backward compatible**
- OAuth users: No change in behavior (still get `OAuthAuthorizationRequiredError`)
- Static token users: Now get sentinel error instead of generic error
- Error messages remain the same
- No breaking changes to public API

## Test Results

```
✅ All transport tests pass (53.6s)
✅ All client tests pass (33.1s)  
✅ Full test suite with race detection passes
✅ No linting errors
✅ Coverage maintained: 69.8% for transport package
```

## Additional Information

This implementation was guided by the existing error handling patterns in the codebase, specifically:
- `ErrSessionTerminated` (sentinel error pattern)
- `OAuthAuthorizationRequiredError` (OAuth 401 handling)
- Existing OAuth tests (test structure)

Both StreamableHTTP and SSE transports now handle 401 responses consistently, making the user experience uniform across transport types.

## Summary by CodeRabbit

* **Bug Fixes**
  * Consolidated 401 error handling across transport methods for consistent behavior and error reporting.
  * Improved error distinction: OAuth-required failures now return appropriate errors distinct from standard unauthorized responses.

* **Tests**
  * Added test coverage for static token authentication with 401 server responses across request and notification paths.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: client/transport/sse.go [hunk 1]
```diff
@@ -162,11 +162,14 @@ func (c *SSE) Start(ctx context.Context) error {
 
 	if resp.StatusCode != http.StatusOK {
 		resp.Body.Close()
-		// Handle OAuth unauthorized error
-		if resp.StatusCode == http.StatusUnauthorized && c.oauthHandler != nil {
-			return &OAuthAuthorizationRequiredError{
-				Handler: c.oauthHandler,
+		// Handle unauthorized error
+		if resp.StatusCode == http.StatusUnauthorized {
```
Comment (dannykopping) [inline client/transport/sse.go]: Nit: this code is repeated and would benefit from extraction into a func, I believe.
