### PR TITLE
fix(tool): Do not return empty `outputSchema`

### LINKED ISSUE #572: bug: v0.39.0 does not work at all
Hi, I have an MCP server that works fine through `stdio` and streamable HTTP in `v0.38.0`, then if I bump to `v0.39.0` it simply stops working in both transports, neither Claude Web nor Claude Desktop work with it, they can't even query the available tools, and no logs are printed anywhere (I guess for obvious reasons in the case of `stdio`).

### PR DESCRIPTION
**Pull request by alejoborbo**
## Description

If the output schema is not specify, we do not return it as we break the MCP specification that are expecting the following format:

```json
  "outputSchema": {
    "type": "object",
    "properties": {},
    "required": []
  }
```

Fixes #572 (if applicable)

## Type of Change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] MCP spec compatibility implementation
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Code refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Tests only (no functional changes)
- [ ] Other (please describe):

## Checklist

- [X] My code follows the code style of this project
- [X] I have performed a self-review of my own code
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the documentation accordingly

## MCP Spec Compliance

- [ ] This PR implements a feature defined in the MCP specification
- [ ] Link to relevant spec section: [Link text](https://modelcontextprotocol.io/specification/path-to-section)
- [ ] Implementation follows the specification exactly

## Summary by CodeRabbit

- Bug Fixes
  - Tool JSON now omits the outputSchema field unless an explicit output schema is provided, reducing noise and avoiding misleading metadata; behavior remains unchanged when a schema is defined.

- Tests
  - Added table-driven tests that marshal tools to JSON and verify outputSchema is present only when expected, validating observable JSON rather than internal fields.

### CODE REVIEW

File: mcp/tools_test.go [hunk 1]
```diff
@@ -586,27 +586,51 @@ func TestToolWithOutputSchema(t *testing.T) {
...
+				WithDescription("Test tool with output schema"),
+				WithOutputSchema[TestOutput](),
+				WithString("input", Required()),
+			),
+			expectedOutputSchema: true,
+		},
+		{
+			name: "no output schema is set",
+			tool: NewTool("test_tool",
+				WithDescription("Test tool with output schema"),
```
Comment (ezynda3) [inline mcp/tools_test.go]: typo?

**Comment by ezynda3** [comment]
@alex210501 I'll merge as soon as the typo is fixed

File: mcp/tools_test.go (hunk 1 above)
Comment (alejoborbo) [reply mcp/tools_test.go]: done in 4fee9866541000918c16af16c6c7a1a0946635b3
